# Pandas

# file Read Write operation

In [1]:
import numpy as np
import pandas as pd

In [4]:
import pandas as pd

draft1 = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex1.csv')    # Supply the file name (path)

draft1.head()

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
draft2 = pd.read_table('C:/Users/suraj/Downloads/examples/test.tsv')  # Read a tsv into a DataFrame

draft2.head()

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [8]:
pd.read_table(r'C:\Users\suraj\Downloads\examples/ex1.csv')

  a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [9]:
pd.read_table(r'C:\Users\suraj\Downloads\examples/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [10]:
pd.read_csv(r'C:\Users\suraj\Downloads\examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [14]:
df =pd.read_csv(r'C:\Users\suraj\Downloads\examples/ex2.csv', names=['col1','col2', 'col3', 'col4', 'col5'])
df

   col1  col2  col3  col4   col5
0     1     2     3     4  hello
1     5     6     7     8  world
2     9    10    11    12    foo

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
parsed = pd.read_csv(r'C:\Users\suraj\Downloads\examples\csv_mindex.csv')
parsed

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [17]:
parsed = pd.read_csv(r'C:\Users\suraj\Downloads\examples\csv_mindex.csv',index_col=['key1'])
parsed

     key2  value1  value2
key1
one     a       1       2
one     b       3       4
one     c       5       6
one     d       7       8
two     a       9      10
two     b      11      12
two     c      13      14
two     d      15      16

In [19]:

parsed = pd.read_csv(r'C:\Users\suraj\Downloads\examples\csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [20]:
pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex4.csv')

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [21]:
pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [22]:
result = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [24]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [25]:
result = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex5.csv', na_values=['one'])
result

  something  a   b     c   d message
0       NaN  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [27]:
result = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex5.csv', na_values=['two',1,2])
result

  something    a     b     c   d message
0       one  NaN   NaN   3.0   4     NaN
1       NaN  5.0   6.0   NaN   8   world
2     three  9.0  10.0  11.0  12     foo

In [31]:
draft3 = pd.read_excel(r'C:\Users\suraj\Downloads\examples\ex1.xlsx') # read excel file

draft3.head()

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [33]:
#draft3 = pd.read_excel(r'C:\Users\suraj\Downloads\examples\ex1.xlsx', sheet_name='my_spends') # read excel file from othersheet

In [36]:
url = "http://www.basketball-reference.com/leagues/NBA_2015_totals.html" # only read tabular datasetb

BB_data = pd.read_html(url)         # Read data from the specified url
BB_data

#BB_data[0].ix[:, 0:20].head(5)      # Check 5 rows (10 columns only)

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [37]:
type(BB_data)

list

In [38]:
len(BB_data)

1

In [39]:
BB_data[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [41]:
BB_data[0].head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035

In [2]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')

In [3]:
titanic_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [4]:
titanic_train[["Name","Pclass"]]

                                                  Name  Pclass
0                              Braund, Mr. Owen Harris       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                               Heikkinen, Miss. Laina       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                             Allen, Mr. William Henry       3
..                                                 ...     ...
151                  Pears, Mrs. Thomas (Edith Wearne)       1
152                                   Meo, Mr. Alfonzo       3
153                    van Billiard, Mr. Austin Blyler       3
154                              Olsen, Mr. Ole Martin       3
155                        Williams, Mr. Charles Duane       1

[156 rows x 2 columns]

In [7]:
type(titanic_train[['Name', 'Pclass']])

pandas.core.frame.DataFrame

In [8]:
titanic_train['Ticket']

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
151              113776
152          A.5. 11206
153            A/5. 851
154           Fa 265302
155            PC 17597
Name: Ticket, Length: 156, dtype: object

In [9]:
type(titanic_train['Ticket'])

pandas.core.series.Series

In [10]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
pd.options.display.max_rows = 10

In [12]:
result = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [13]:
pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex6.csv', nrows=5) # not load whole data just give 5 data

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [14]:
chunk = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex6.csv', chunksize=1000)  # prefer to avoid chunksize
chunk

Writing Data to Text Format

In [15]:
data = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [16]:
data.to_csv(r'C:\Users\suraj\Downloads\examples\out.csv') # to store data

In [17]:
import sys
data.to_csv(r'C:\Users\suraj\Downloads\examples\out1.csv', sep='@') # to store data with @ sep

In [104]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [18]:
data.to_csv(r'C:\Users\suraj\Downloads\examples\out2.csv', index=False, header=False) # remove index

In [19]:
data.to_csv(r'C:\Users\suraj\Downloads\examples\out3.csv', index=False, columns=['a', 'b', 'c'])

In [21]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv(r'C:\Users\suraj\Downloads\examples\tseries.csv')
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int32

Working with Delimited Formats

In [22]:
import csv
f = open(r'C:\Users\suraj\Downloads\examples\ex7.csv')  # read the file wit diff method

reader = csv.reader(f)
reader
# this is iterable object

In [23]:
for i in reader:
    print(i)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [24]:
# another method to read file
with open(r'C:\Users\suraj\Downloads\examples\ex7.csv') as f:
    lines = list(csv.reader(f))
print(lines)

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [25]:
lines[0]

['a', 'b', 'c']

In [26]:
lines[1]

['1', '2', '3']

In [27]:
header, values = lines[0], lines[1:]

In [28]:
header

['a', 'b', 'c']

In [29]:
values

[['1', '2', '3'], ['1', '2', '3']]

In [31]:
# zip
l=[1,2,3, 4]
l1=[5,6,7,8]

for i in zip(l,l1):
    print(i)

(1, 5)
(2, 6)
(3, 7)
(4, 8)

In [32]:
for i in zip(values):
    print(i)

(['1', '2', '3'],)
(['1', '2', '3'],)

In [33]:
for i in zip(*values):
    print(i)

('1', '1')
('2', '2')
('3', '3')

In [34]:
for i in zip(header, zip(*values)):
    print(i)

('a', ('1', '1'))
('b', ('2', '2'))
('c', ('3', '3'))

In [36]:
d ={}
for i,j in zip(header, zip(*values)):
    d[i] = j
    
d

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [35]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

JSON Data

In [37]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [41]:
type(obj)

str

In [38]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [39]:
type(result)

dict

In [40]:
asjson = json.dumps(result)  # again convert into str
type(asjson)
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [42]:
pd.DataFrame(result['siblings'])

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [43]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age','pets'])
siblings

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [44]:
data = pd.read_json(r'C:\Users\suraj\Downloads\examples\example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [45]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

XML and HTML: Web Scraping

In [50]:
tables = pd.read_html("file:///C:/Users/suraj/Downloads/examples/fdic_failed_bank_list.html")
len(tables)

#failures.head()
tables[0]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"
...,...,...,...,...,...,...,...
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014"
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002"
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003"
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005"
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005"

In [53]:
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [54]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [55]:

close_timestamps.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

In [56]:
close_timestamps.dt.day.value_counts()

23    31
30    30
19    30
20    27
17    23
      ..
12    10
9     10
31     8
1      8
3      3
Name: Closing Date, Length: 31, dtype: int64

# Binary Data Formats

In [57]:
frame = pd.read_csv(r'C:\Users\suraj\Downloads\examples\ex1.csv')  # ser - obj to byte code (main memory to hard disk)
frame
frame.to_pickle(r'C:\Users\suraj\Downloads\examples\frame_pickle')  # deser - bytecode to obj( hard disk to main memory)

In [58]:
pd.read_pickle(r'C:\Users\suraj\Downloads\examples\/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Using HDF5 Format

In [60]:
frame = pd.DataFrame({'a': np.random.randn(100)})
frame

           a
0  -0.264927
1   0.064453
2   1.460811
3   0.155146
4  -0.509964
..       ...
95  0.589374
96 -0.550225
97  1.905336
98 -0.311647
99 -0.499567

[100 rows x 1 columns]

In [61]:

store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [62]:
store['obj1']

           a
0  -0.264927
1   0.064453
2   1.460811
3   0.155146
4  -0.509964
..       ...
95  0.589374
96 -0.550225
97  1.905336
98 -0.311647
99 -0.499567

[100 rows x 1 columns]

In [63]:
store['obj1_col']

0    -0.264927
1     0.064453
2     1.460811
3     0.155146
4    -0.509964
        ...
95    0.589374
96   -0.550225
97    1.905336
98   -0.311647
99   -0.499567
Name: a, Length: 100, dtype: float64

In [64]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])
store.close()

In [65]:
frame.to_hdf('mydata.h5', 'obj3', format='table')
pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

          a
0 -0.264927
1  0.064453
2  1.460811
3  0.155146
4 -0.509964

# Web APIs

In [3]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [4]:
pd.read_csv(url)  # data in json form can't read with csv

Empty DataFrame
Columns: [[{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/41307", repository_url:"https://api.github.com/repos/pandas-dev/pandas", labels_url:"https://api.github.com/repos/pandas-dev/pandas/issues/41307/labels{/name}", comments_url:"https://api.github.com/repos/pandas-dev/pandas/issues/41307/comments", events_url:"https://api.github.com/repos/pandas-dev/pandas/issues/41307/events", html_url:"https://github.com/pandas-dev/pandas/pull/41307", id:875526640, node_id:"MDExOlB1bGxSZXF1ZXN0NjI5ODUxODQy", number:41307, title:"Deprecate inplace in Categorical.set_categories.", user:{"login":"OlehKSS", id:16047980, node_id:"MDQ6VXNlcjE2MDQ3OTgw", avatar_url:"https://avatars.githubusercontent.com/u/16047980?v=4", gravatar_id:"", url:"https://api.github.com/users/OlehKSS", html_url:"https://github.com/OlehKSS", followers_url:"https://api.github.com/users/OlehKSS/followers", following_url:"https://api.github.com/users/OlehKSS/following{/other_user}", gists_url:"https://api.github.com/users/OlehKSS/gists{/gist_id}", starred_url:"https://api.github.com/users/OlehKSS/starred{/owner}{/repo}", subscriptions_url:"https://api.github.com/users/OlehKSS/subscriptions", organizations_url:"https://api.github.com/users/OlehKSS/orgs", repos_url:"https://api.github.com/users/OlehKSS/repos", events_url:"https://api.github.com/users/OlehKSS/events{/privacy}", received_events_url:"https://api.github.com/users/OlehKSS/received_events", type:"User", site_admin:false}, labels:[], state:"open", locked:false, assignee:null, assignees:[], milestone:null, comments:0, created_at:"2021-05-04T14:33:56Z", updated_at:"2021-05-04T14:33:56Z", closed_at:null, author_association:"CONTRIBUTOR", active_lock_reason:null, pull_request:{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/41307", html_url:"https://github.com/pandas-dev/pandas/pull/41307".1, diff_url:"https://github.com/pandas-dev/pandas/pull/41307.diff", patch_url:"https://github.com/pandas-dev/pandas/pull/41307.patch"}, body:"- [x] xref #37643\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [x] whatsnew entry\r\n", performed_via_github_app:null}, {"url":"https://api.github.com/repos/pandas-dev/pandas/issues/41306", repository_url:"https://api.github.com/repos/pandas-dev/pandas".1, labels_url:"https://api.github.com/repos/pandas-dev/pandas/issues/41306/labels{/name}", comments_url:"https://api.github.com/repos/pandas-dev/pandas/issues/41306/comments", events_url:"https://api.github.com/repos/pandas-dev/pandas/issues/41306/events", html_url:"https://github.com/pandas-dev/pandas/pull/41306", id:875411663, node_id:"MDExOlB1bGxSZXF1ZXN0NjI5NzU5NTU2", number:41306, title:"[ArrowStringArray] CLN: assorted cleanup", user:{"login":"simonjayhawkins", id:13159005, node_id:"MDQ6VXNlcjEzMTU5MDA1", avatar_url:"https://avatars.githubusercontent.com/u/13159005?v=4", gravatar_id:"".1, url:"https://api.github.com/users/simonjayhawkins", html_url:"https://github.com/simonjayhawkins", followers_url:"https://api.github.com/users/simonjayhawkins/followers", following_url:"https://api.github.com/users/simonjayhawkins/following{/other_user}", gists_url:"https://api.github.com/users/simonjayhawkins/gists{/gist_id}", starred_url:"https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}", subscriptions_url:"https://api.github.com/users/simonjayhawkins/subscriptions", organizations_url:"https://api.github.com/users/simonjayhawkins/orgs", repos_url:"https://api.github.com/users/simonjayhawkins/repos", events_url:"https://api.github.com/users/simonjayhawkins/events{/privacy}", received_events_url:"https://api.github.com/users/simonjayhawkins/received_events", type:"User".1, site_admin:false}.1, labels:[{"id":57522093, node_id:"MDU6TGFiZWw1NzUyMjA5Mw==", url:"https://api.github.com/repos/pandas-dev/pandas/labels/Strings", name:"Strings", color:"5319e7", default:false, description:"String extension data type and string data"}], state:"open".1, locked:false.1, assignee:null.1, assignees:[].1, milestone:null.1, comments:0.1, created_at:"2021-05-04T12:27:42Z", updated_at:"2021-05-04T14:18:49Z", closed_at:null.1, author_association:"MEMBER", active_lock_reason:null.1, pull_request:{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/41306", html_url:"https://github.com/pandas-dev/pandas/pull/41306".1, diff_url:"https://github.com/pandas-dev/pandas/pull/41306.diff", patch_url:"https://github.com/pandas-dev/pandas/pull/41306.patch"}, body:"seperate commits for cleanups\r\n\r\nremove hasattr for str methods available in pyarrow 1.0.0\r\nadd comments to indicate pyarrow version a method is addded.\r\nde-duplicate fixture\r\nde-duplicate warning from str.contains with pattern with capture groups\r\nremove special casing StringDtype ", performed_via_github_app:null}.1, {"url":"https://api.github.com/repos/pandas-dev/pandas/issues/41305", repository_url:"https://api.github.com/repos/pandas-dev/pandas".2, ...]
Index: []

[0 rows x 2274 columns]

In [5]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41307',
  'id': 875526640,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjI5ODUxODQy',
  'number': 41307,
  'title': 'Deprecate inplace in Categorical.set_categories.',
  'user': {'login': 'OlehKSS',
   'id': 16047980,
   'node_id': 'MDQ6VXNlcjE2MDQ3OTgw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/16047980?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/OlehKSS',
   'html_url': 'https://github.com/OlehKSS',
   'followers_url': 'https://api.github.com/users/OlehKSS/followers',
   'following_url': 'https://api.github.com/users/OlehKSS/following{/other_user}',
   'gists_url': 'https://api.github.com/users/OlehKSS/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/OlehKSS/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/OlehKSS/subscriptions',
   'organizations_url': 'https://api.github.com/users/OlehKSS/orgs',
   'repos_url': 'https://api.github.com/users/OlehKSS/repos',
   'events_url': 'https://api.github.com/users/OlehKSS/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/OlehKSS/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-05-04T14:33:56Z',
  'updated_at': '2021-05-04T14:33:56Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41307',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41307',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41307.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41307.patch'},
  'body': '- [x] xref #37643\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [x] whatsnew entry\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41306',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41306/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41306/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41306/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41306',
  'id': 875411663,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjI5NzU5NTU2',
  'number': 41306,
  'title': '[ArrowStringArray] CLN: assorted cleanup',
  'user': {'login': 'simonjayhawkins',
   'id': 13159005,
   'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/simonjayhawkins',
   'html_url': 'https://github.com/simonjayhawkins',
   'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
   'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
   'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
   'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
   'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
   'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 57522093,
    'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings',
    'name': 'Strings',
    'color': '5319e7',
    'default': False,
    'description': 'String extension data type and string data'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-05-04T12:27:42Z',
  'updated_at': '2021-05-04T14:18:49Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41306',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41306',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41306.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41306.patch'},
  'body': 'seperate commits for cleanups\r\n\r\nremove hasattr for str methods available in pyarrow 1.0.0\r\nadd comments to indicate pyarrow version a method is addded.\r\nde-duplicate fixture\r\nde-duplicate warning from str.contains with pattern with capture groups\r\nremove special casing StringDtype ',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41305',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41305/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41305/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41305/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/41305',
  'id': 875371042,
  'node_id': 'MDU6SXNzdWU4NzUzNzEwNDI=',
  'number': 41305,
  'title': "BUG: shared doc string decorator doesn't handle args defined with sets",
  'user': {'login': 'attack68',
   'id': 24256554,
   'node_id': 'MDQ6VXNlcjI0MjU2NTU0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/attack68',
   'html_url': 'https://github.com/attack68',
   'followers_url': 'https://api.github.com/users/attack68/followers',
   'following_url': 'https://api.github.com/users/attack68/following{/other_user}',
   'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',
   'organizations_url': 'https://api.github.com/users/attack68/orgs',
   'repos_url': 'https://api.github.com/users/attack68/repos',
   'events_url': 'https://api.github.com/users/attack68/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/attack68/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 134699,
    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',
    'name': 'Docs',
    'color': '3465A4',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-05-04T11:33:01Z',
  'updated_at': '2021-05-04T11:33:01Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': 'I was exploring using a shared docstring decorator today and came up with the issue that the pandas notation for parameter sets is the same as needed for string replacement. So for example:\r\n\r\n```\r\n@doc(param1="some_value")\r\ndef test_doc_replacement(self, set_ars):\r\n    """\r\n    Description of {param1}\r\n\r\n    Parameters\r\n    ----------\r\n    set_args : {\'str1\', \'str2_or\', \'str3\'}\r\n        string values from a set.\r\n\r\n    Returns\r\n    -------\r\n    A KeyError!!\r\n    """\r\n    pass\r\n```\r\n\r\nYielded a KeyError, since its tries to find a key `"\'str1\', \'str2_or\', \'str3\'", in my docstring parameters.\r\nThe way I\'m attempting to get around it is:\r\n\r\n```\r\n@doc(param1="some_value", set_args="{\'str1\', \'str2_or\', \'str3\'}")\r\ndef test_doc_replacement(self, set_ars):\r\n    """\r\n    Description of {param1}\r\n\r\n    Parameters\r\n    ----------\r\n    set_args : {set_args}\r\n         string values from a set.\r\n\r\n    Returns\r\n    -------\r\n    Hopefully the right display.\r\n    """\r\n    pass\r\n```\r\n\r\nIncidentally anywhere in the docs that a `{}` appears seems to be a problem. So in my examples section I also had to try changing:\r\n\r\n`>>> df = DataFrame({\'A\': [1,2], \'B\': [3,4]})`\r\n\r\nto \r\n\r\n`>>> df = DataFrame([[1,3],[2,4]], columns=["A", "B"])`',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41304',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41304/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41304/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41304/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/41304',
  'id': 875344536,
  'node_id': 'MDU6SXNzdWU4NzUzNDQ1MzY=',
  'number': 41304,
  'title': 'BUG: Incorrect parsing csv header line if no separator in the end',
  'user': {'login': 'dimka11',
   'id': 6096108,
   'node_id': 'MDQ6VXNlcjYwOTYxMDg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6096108?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/dimka11',
   'html_url': 'https://github.com/dimka11',
   'followers_url': 'https://api.github.com/users/dimka11/followers',
   'following_url': 'https://api.github.com/users/dimka11/following{/other_user}',
   'gists_url': 'https://api.github.com/users/dimka11/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/dimka11/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/dimka11/subscriptions',
   'organizations_url': 'https://api.github.com/users/dimka11/orgs',
   'repos_url': 'https://api.github.com/users/dimka11/repos',
   'events_url': 'https://api.github.com/users/dimka11/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/dimka11/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-05-04T10:56:22Z',
  'updated_at': '2021-05-04T12:17:20Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\ncsv lines (header line and first data line):\r\n\r\n"Местное время в Омске / им. Д. М. Карбышева (аэропорт)";"T";"Po";"P";"Pa";"U";"DD";"Ff";"ff10";"ff3";"N";"WW";"W1";"W2";"Tn";"Tx";"Cl";"Nh";"H";"Cm";"Ch";"VV";"Td";"RRR";"tR";"E";"Tg";"E\'";"sss"\r\n"04.05.2021 09:00";"9.8";"759.0";"";"";"68";"Ветер, дующий с запада";"3";"";"";"Облаков нет.";" ";"";"";"-0.3";"";"";"";"";"";"";"20.0";"";"Осадков нет";"12";"";"";"";"";\r\n\r\n```python\r\n\r\nimport pandas as pd\r\ndf = pd.read_csv(\'28699.01.12.2019.04.05.2021.1.0.0.ru.utf8.00000000.csv\', sep=\';\', skiprows=6, index_col=0)\r\ndf.info()\r\n\r\ndf[\'T\']\r\n\r\ndf.head(1)\r\n\r\n```\r\n\r\n#### Problem description\r\n\r\nWhen there is no separator at the end of the header line, pandas seems like skip first column (T) and shows second column instead.\r\n\r\nOutput:\r\n\r\n<class \'pandas.core.frame.DataFrame\'>\r\nIndex: 4046 entries, 04.05.2021 09:00 to 01.12.2019 00:00\r\nData columns (total 29 columns):\r\n    Column                                                  Non-Null Count  Dtype  \r\n---  ------                                                  --------------  -----  \r\n 0   Местное время в Омске / им. Д. М. Карбышева (аэропорт)  4037 non-null   float64\r\n 1   T                                                       4042 non-null   float64\r\n 2   Po                                                      0 non-null      float64\r\n\r\n04.05.2021 09:00    759.0\r\n04.05.2021 06:00    757.0\r\n04.05.2021 03:00    756.0\r\n\r\n\r\nМестное время в Омске / им. Д. М. Карбышева (аэропорт)\tT\tPo\tP\tPa\tU\tDD\tFf\tff10\tff3\t...\tCm\tCh\tVV\tTd\tRRR\ttR\tE\tTg\tE\'\tsss\r\n04.05.2021 09:00\t9.8\t759.0\tNaN\tNaN\t68.0\tВетер, дующий с запада\t3.0\tNaN\tNaN\tОблаков нет.\t...\tNaN\t20.0\tNaN\tОсадков нет\t12.0\tNaN\tNaN\tNaN\tNaN\tNaN\r\n\r\n\r\n#### Expected Output\r\n\r\nAfter manually added " ; " separator in the end of the header line result was as excepted:\r\n\r\n<class \'pandas.core.frame.DataFrame\'>\r\nIndex: 4046 entries, 04.05.2021 09:00 to 01.12.2019 00:00\r\nData columns (total 29 columns):\r\n    Column       Non-Null Count  Dtype  \r\n---  ------       --------------  -----  \r\n 0   T            4037 non-null   float64\r\n 1   Po           4042 non-null   float64\r\n\r\nМестное время в Омске / им. Д. М. Карбышева (аэропорт)\r\n04.05.2021 09:00     9.8\r\n04.05.2021 06:00     1.5\r\n04.05.2021 03:00     2.2\r\n04.05.2021 00:00     6.2\r\n\r\n\r\nT | Po | P | Pa | U | DD | Ff | ff10 | ff3 | N | ... | Ch | VV | Td | RRR | tR | E | Tg | E\' | sss | Unnamed: 29\r\n-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --\r\n\r\n9.8 | 759.0 | NaN | NaN | 68.0 | Ветер, дующий с запада | 3.0 | NaN | NaN | Облаков нет. | ... | NaN | 20.0 | NaN | Осадков нет | 12.0 | NaN | NaN | NaN | NaN | NaN\r\n\r\n\r\n\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : b5958ee1999e9aead1938c0bba2b674378807b3d\r\npython           : 3.6.8.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.21354\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.None\r\n\r\npandas           : 1.1.5\r\nnumpy            : 1.17.4\r\npytz             : 2018.9\r\ndateutil         : 2.8.1\r\npip              : 19.0.3\r\nsetuptools       : 42.0.1\r\nCython           : 0.29.21\r\npytest           : 6.2.3\r\nhypothesis       : None\r\nsphinx           : 3.5.4\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.4.1\r\nhtml5lib         : 1.0.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.10\r\nIPython          : 7.5.0\r\npandas_datareader: None\r\nbs4              : 4.7.1\r\nbottleneck       : 1.3.1\r\nfsspec           : 0.6.1\r\nfastparquet      : None\r\ngcsfs            : 0.5.0\r\nmatplotlib       : 3.1.2\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : 2.6.1\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.2.1\r\nsqlalchemy       : 1.2.18\r\ntables           : None\r\ntabulate         : None\r\nxarray           : 0.14.1\r\nxlrd             : 1.2.0\r\nxlwt             : None\r\nnumba            : 0.48.0\r\n\r\n</details>\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41301',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41301/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41301/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41301/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41301',
  'id': 875056218,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjI5NDgwMzk2',
  'number': 41301,
  'title': 'COMPAT: frame round error msg for py310',
  'user': {'login': 'fangchenli',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/fangchenli',
   'html_url': 'https://github.com/fangchenli',
   'followers_url': 'https://api.github.com/users/fangchenli/followers',
   'following_url': 'https://api.github.com/users/fangchenli/following{/other_user}',
   'gists_url': 'https://api.github.com/users/fangchenli/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/fangchenli/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/fangchenli/subscriptions',
   'organizations_url': 'https://api.github.com/users/fangchenli/orgs',
   'repos_url': 'https://api.github.com/users/fangchenli/repos',
   'events_url': 'https://api.github.com/users/fangchenli/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/fangchenli/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 2955636717,
    'node_id': 'MDU6TGFiZWwyOTU1NjM2NzE3',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Python%203.10',
    'name': 'Python 3.10',
    'color': 'fef2c0',
    'default': False,
    'description': 'Python dev version'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-05-04T02:47:57Z',
  'updated_at': '2021-05-04T12:43:16Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41301',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41301',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41301.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41301.patch'},

In [6]:
data[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41307/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/41307',
 'id': 875526640,
 'node_id': 'MDExOlB1bGxSZXF1ZXN0NjI5ODUxODQy',
 'number': 41307,
 'title': 'Deprecate inplace in Categorical.set_categories.',
 'user': {'login': 'OlehKSS',
  'id': 16047980,
  'node_id': 'MDQ6VXNlcjE2MDQ3OTgw',
  'avatar_url': 'https://avatars.githubusercontent.com/u/16047980?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/OlehKSS',
  'html_url': 'https://github.com/OlehKSS',
  'followers_url': 'https://api.github.com/users/OlehKSS/followers',
  'following_url': 'https://api.github.com/users/OlehKSS/following{/other_user}',
  'gists_url': 'https://api.github.com/users/OlehKSS/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/OlehKSS/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/OlehKSS/subscriptions',
  'organizations_url': 'https://api.github.com/users/OlehKSS/orgs',
  'repos_url': 'https://api.github.com/users/OlehKSS/repos',
  'events_url': 'https://api.github.com/users/OlehKSS/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/OlehKSS/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2021-05-04T14:33:56Z',
 'updated_at': '2021-05-04T14:33:56Z',
 'closed_at': None,
 'author_association': 'CONTRIBUTOR',
 'active_lock_reason': None,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41307',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41307',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/41307.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/41307.patch'},
 'body': '- [x] xref #37643\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [x] whatsnew entry\r\n',
 'performed_via_github_app': None}

In [7]:
len(data)

30

In [8]:
data[0]['url']

'https://api.github.com/repos/pandas-dev/pandas/issues/41307'

In [9]:
data[0]['user']

{'login': 'OlehKSS',
 'id': 16047980,
 'node_id': 'MDQ6VXNlcjE2MDQ3OTgw',
 'avatar_url': 'https://avatars.githubusercontent.com/u/16047980?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/OlehKSS',
 'html_url': 'https://github.com/OlehKSS',
 'followers_url': 'https://api.github.com/users/OlehKSS/followers',
 'following_url': 'https://api.github.com/users/OlehKSS/following{/other_user}',
 'gists_url': 'https://api.github.com/users/OlehKSS/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/OlehKSS/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/OlehKSS/subscriptions',
 'organizations_url': 'https://api.github.com/users/OlehKSS/orgs',
 'repos_url': 'https://api.github.com/users/OlehKSS/repos',
 'events_url': 'https://api.github.com/users/OlehKSS/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/OlehKSS/received_events',
 'type': 'User',
 'site_admin': False}

In [10]:
data[0]['user']['id']

16047980

In [11]:
pd.DataFrame(data).head()

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,pull_request,body,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/41307,875526640,MDExOlB1bGxSZXF1ZXN0NjI5ODUxODQy,41307,Deprecate inplace in Categorical.set_categories.,...,None,0,2021-05-04T14:33:56Z,2021-05-04T14:33:56Z,None,CONTRIBUTOR,None,{'url': 'https://api.github.com/repos/pandas-d...,- [x] xref #37643\r\n- [x] tests added / passe...,None
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/41306,875411663,MDExOlB1bGxSZXF1ZXN0NjI5NzU5NTU2,41306,[ArrowStringArray] CLN: assorted cleanup,...,None,0,2021-05-04T12:27:42Z,2021-05-04T14:18:49Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,seperate commits for cleanups\r\n\r\nremove ha...,None
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/41305,875371042,MDU6SXNzdWU4NzUzNzEwNDI=,41305,BUG: shared doc string decorator doesn't handl...,...,None,0,2021-05-04T11:33:01Z,2021-05-04T11:33:01Z,None,CONTRIBUTOR,None,NaN,I was exploring using a shared docstring decor...,None
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/41304,875344536,MDU6SXNzdWU4NzUzNDQ1MzY=,41304,BUG: Incorrect parsing csv header line if no s...,...,None,1,2021-05-04T10:56:22Z,2021-05-04T12:17:20Z,None,NONE,None,NaN,- [x] I have checked that this issue has not a...,None
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/41301,875056218,MDExOlB1bGxSZXF1ZXN0NjI5NDgwMzk2,41301,COMPAT: frame round error msg for py310,...,None,0,2021-05-04T02:47:57Z,2021-05-04T12:43:16Z,None,MEMBER,None,{'url': 'https://api.github.com/repos/pandas-d...,Not sure if this is the desired way to address...,None

In [12]:
pd.DataFrame(data)[['user']]

                                                 user
0   {'login': 'OlehKSS', 'id': 16047980, 'node_id'...
1   {'login': 'simonjayhawkins', 'id': 13159005, '...
2   {'login': 'attack68', 'id': 24256554, 'node_id...
3   {'login': 'dimka11', 'id': 6096108, 'node_id':...
4   {'login': 'fangchenli', 'id': 7614606, 'node_i...
5   {'login': 'jbrockmendel', 'id': 8078968, 'node...
6   {'login': 'jbrockmendel', 'id': 8078968, 'node...
7   {'login': 'jbrockmendel', 'id': 8078968, 'node...
8   {'login': 'jbrockmendel', 'id': 8078968, 'node...
9   {'login': 'kemcbride', 'id': 4368575, 'node_id...
10  {'login': 'jbrockmendel', 'id': 8078968, 'node...
11  {'login': 'simonjayhawkins', 'id': 13159005, '...
12  {'login': 'jbrockmendel', 'id': 8078968, 'node...
13  {'login': 'jbrockmendel', 'id': 8078968, 'node...
14  {'login': 'gregparkes', 'id': 22742021, 'node_...
15  {'login': 'jbrockmendel', 'id': 8078968, 'node...
16  {'login': 'phofl', 'id': 61934744, 'node_id': ...
17  {'login': 'jbrockmendel', 'id': 8078968, 'node...
18  {'login': 'ShaharNaveh', 'id': 50263213, 'node...
19  {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
20  {'login': 'simonjayhawkins', 'id': 13159005, '...
21  {'login': 'Leejung8763', 'id': 50440358, 'node...
22  {'login': 'lrizzello', 'id': 53616818, 'node_i...
23  {'login': 'topper-123', 'id': 26364415, 'node_...
24  {'login': 'attack68', 'id': 24256554, 'node_id...
25  {'login': 'attack68', 'id': 24256554, 'node_id...
26  {'login': 'brunocous', 'id': 2650058, 'node_id...
27  {'login': 'topper-123', 'id': 26364415, 'node_...
28  {'login': 'JoeSchr', 'id': 8218910, 'node_id':...
29  {'login': 'Dr-Irv', 'id': 15113894, 'node_id':...

In [13]:
data = resp.json()
data[2]['user']

{'login': 'attack68',
 'id': 24256554,
 'node_id': 'MDQ6VXNlcjI0MjU2NTU0',
 'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/attack68',
 'html_url': 'https://github.com/attack68',
 'followers_url': 'https://api.github.com/users/attack68/followers',
 'following_url': 'https://api.github.com/users/attack68/following{/other_user}',
 'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',
 'organizations_url': 'https://api.github.com/users/attack68/orgs',
 'repos_url': 'https://api.github.com/users/attack68/repos',
 'events_url': 'https://api.github.com/users/attack68/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/attack68/received_events',
 'type': 'User',
 'site_admin': False}

In [14]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues

,number,title,labels,state
0,41307,Deprecate inplace in Categorical.set_categories.,[],open
1,41306,[ArrowStringArray] CLN: assorted cleanup,"[{'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUy...",open
2,41305,BUG: shared doc string decorator doesn't handl...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
3,41304,BUG: Incorrect parsing csv header line if no s...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
4,41301,COMPAT: frame round error msg for py310,"[{'id': 2955636717, 'node_id': 'MDU6TGFiZWwyOT...",open
5,41300,"CLN: more descriptive names, annotations in gr...","[{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...",open
6,41299,TYP: BaseWindowGroupby._grouper,"[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...",open
7,41298,REF: raise more selectively in libreduction,"[{'id': 2365504383, 'node_id': 'MDU6TGFiZWwyMz...",open
8,41297,DEPR: pd.Grouper?,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
9,41295,DOC: Validator + converting array_like to arra...,[],open
10,41294,REF: support object dtype in libgroupby.group_add,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
11,41293,[ArrowStringArray] REF: pre-cursor to adding r...,"[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
12,41292,BUG: fix suppressed TypeErrors in Groupby.mean...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
13,41291,API: SeriesGroupBy.product with numeric_only a...,"[{'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNz...",open
14,41290,ENH: pandas.Series.apply method to work with m...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
15,41289,REF: Share py_fallback,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
16,41288,Bug in iloc.setitem orienting IntegerArray int...,"[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...",open
17,41287,REF: Avoid fallback in GroupBy._agg_general,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
18,41284,DOC: Fix docs for io/json/*,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
19,41283,TYP Series and DataFrame currently type-check ...,"[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...",open
20,41281,[ArrowStringArray] PERF: isin using native pya...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
21,41277,QST: Pandas describe() methods(with float16 an...,"[{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...",open
22,41276,QST: Efficiently stylizing and appending new d...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
23,41272,ENH: Indexes with any numpy int/uint/float dtype,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
24,41269,ENH: make `Styler` compatible with non-unique ...,"[{'id': 1728592794, 'node_id': 'MDU6TGFiZWwxNz...",open
25,41266,API: make `hide_columns` and `hide_index` have...,"[{'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNz...",open
26,41264,BUG: specifying fill_value in pandas.DataFrame...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
27,41263,BUG: RangeIndex.astype('category'),"[{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...",open
28,41259,fix(documentation/user_guides/indexing): Highl...,[],open
29,41258,TYP: Typing for ExtensionArray.__getitem__,"[{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...",open

In [15]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp
d1 = resp.json()
masterDF = pd.DataFrame(columns=['id','node_id','url','name','color','default','description'])

for i in range(30):
    s=pd.DataFrame(d1[i]['labels'], columns= ['id','node_id','url','name','color','default','description'])
    masterDF = masterDF.append(s, ignore_index = True)
masterDF

,id,node_id,url,name,color,default,description
0,76811,MDU6TGFiZWw3NjgxMQ==,https://api.github.com/repos/pandas-dev/pandas...,Bug,e10c02,False,None
1,1954720290,MDU6TGFiZWwxOTU0NzIwMjkw,https://api.github.com/repos/pandas-dev/pandas...,Needs Triage,0052cc,False,Issue that has not been reviewed by a pandas t...
2,57522093,MDU6TGFiZWw1NzUyMjA5Mw==,https://api.github.com/repos/pandas-dev/pandas...,Strings,5319e7,False,String extension data type and string data
3,76811,MDU6TGFiZWw3NjgxMQ==,https://api.github.com/repos/pandas-dev/pandas...,Bug,e10c02,False,None
4,134699,MDU6TGFiZWwxMzQ2OTk=,https://api.github.com/repos/pandas-dev/pandas...,Docs,3465A4,False,None
5,1954720290,MDU6TGFiZWwxOTU0NzIwMjkw,https://api.github.com/repos/pandas-dev/pandas...,Needs Triage,0052cc,False,Issue that has not been reviewed by a pandas t...
6,76811,MDU6TGFiZWw3NjgxMQ==,https://api.github.com/repos/pandas-dev/pandas...,Bug,e10c02,False,None
7,1954720290,MDU6TGFiZWwxOTU0NzIwMjkw,https://api.github.com/repos/pandas-dev/pandas...,Needs Triage,0052cc,False,Issue that has not been reviewed by a pandas t...
8,2955636717,MDU6TGFiZWwyOTU1NjM2NzE3,https://api.github.com/repos/pandas-dev/pandas...,Python 3.10,fef2c0,False,Python dev version
9,211029535,MDU6TGFiZWwyMTEwMjk1MzU=,https://api.github.com/repos/pandas-dev/pandas...,Clean,207de5,False,None
10,233160,MDU6TGFiZWwyMzMxNjA=,https://api.github.com/repos/pandas-dev/pandas...,Groupby,729FCF,False,None
11,1280988427,MDU6TGFiZWwxMjgwOTg4NDI3,https://api.github.com/repos/pandas-dev/pandas...,Typing,ea91a4,False,mypy type annotations
12,1045950827,MDU6TGFiZWwxMDQ1OTUwODI3,https://api.github.com/repos/pandas-dev/pandas...,Window,d4c5f9,False,"rolling, ewma, expanding"
13,2365504383,MDU6TGFiZWwyMzY1NTA0Mzgz,https://api.github.com/repos/pandas-dev/pandas...,Reductions,547c03,False,Reduction operations
14,127681,MDU6TGFiZWwxMjc2ODE=,https://api.github.com/repos/pandas-dev/pandas...,Refactor,FCE94F,False,Internal refactoring of code
15,87485152,MDU6TGFiZWw4NzQ4NTE1Mg==,https://api.github.com/repos/pandas-dev/pandas...,Deprecate,5319e7,False,Functionality to remove in pandas
16,219960758,MDU6TGFiZWwyMTk5NjA3NTg=,https://api.github.com/repos/pandas-dev/pandas...,Needs Discussion,207de5,False,None
17,233160,MDU6TGFiZWwyMzMxNjA=,https://api.github.com/repos/pandas-dev/pandas...,Groupby,729FCF,False,None
18,127681,MDU6TGFiZWwxMjc2ODE=,https://api.github.com/repos/pandas-dev/pandas...,Refactor,FCE94F,False,Internal refactoring of code
19,57522093,MDU6TGFiZWw1NzUyMjA5Mw==,https://api.github.com/repos/pandas-dev/pandas...,Strings,5319e7,False,String extension data type and string data
20,233160,MDU6TGFiZWwyMzMxNjA=,https://api.github.com/repos/pandas-dev/pandas...,Groupby,729FCF,False,None
21,1741841389,MDU6TGFiZWwxNzQxODQxMzg5,https://api.github.com/repos/pandas-dev/pandas...,API - Consistency,b60205,False,Internal Consistency of API/Behavior
22,35818298,MDU6TGFiZWwzNTgxODI5OA==,https://api.github.com/repos/pandas-dev/pandas...,API Design,AD7FA8,False,None
23,76811,MDU6TGFiZWw3NjgxMQ==,https://api.github.com/repos/pandas-dev/pandas...,Bug,e10c02,False,None
24,233160,MDU6TGFiZWwyMzMxNjA=,https://api.github.com/repos/pandas-dev/pandas...,Groupby,729FCF,False,None
25,2365523662,MDU6TGFiZWwyMzY1NTIzNjYy,https://api.github.com/repos/pandas-dev/pandas...,Nuisance Columns,120491,False,Identifying/Dropping nuisance columns in reduc...
26,76812,MDU6TGFiZWw3NjgxMg==,https://api.github.com/repos/pandas-dev/pandas...,Enhancement,4E9A06,False,None
27,1954720290,MDU6TGFiZWwxOTU0NzIwMjkw,https://api.github.com/repos/pandas-dev/pandas...,Needs Triage,0052cc,False,Issue that has not been reviewed by a pandas t...
28,233160,MDU6TGFiZWwyMzMxNjA=,https://api.github.com/repos/pandas-dev/pandas...,Groupby,729FCF,False,None
29,127681,MDU6TGFiZWwxMjc2ODE=,https://api.github.com/repos/pandas-dev/pandas...,Refactor,FCE94F,False,Internal refactoring of code
30,2822098,MDU6TGFiZWwyODIyMDk4,https://api.github.com/repos/pandas-dev/pandas...,Indexing,0b02e1,False,"Related to indexing on series/frames, not to i..."
31,1817503692,MDU6TGFiZWwxODE3NTAzNjky,https://api.github.com/repos/pandas-dev/pandas...,NA - MaskedArrays,8cc645,False,Related to pd.NA and nullable extension arrays
32,233160,MDU6TGFiZWwyMzMxNjA=,https://api.github.com/repos/pandas-dev/pandas...,Groupby,729FCF,False,None
33,134699,MDU6TGFiZWwxMzQ2OTk=,https://api.github.com/repos/pandas-dev/pandas...,Docs,3465A4,False,None
34,49379259,MDU6TGFiZWw0OTM3OTI1OQ==,https://api.github.com/repos/pandas-dev/pandas...,IO JSON,207de5,False,"read_json, to_json, json_normalize"
35,1280988427,MDU6TGFiZWwxMjgwOTg4NDI3,https://api.github.com/repos/pandas-dev/pandas...,Typing,ea91a4,False,mypy type annotations
36,8935311,MDU6TGFiZWw4OTM1MzEx,https://api.github.com/repos/pandas-dev/pandas...,Performance,a10c02,False,Memory or execution speed performance
37,57522093,MDU6TGFiZWw1NzUyMjA5Mw==,https://api.github.com/repos/pandas-dev/pandas...,Strings,5319e7,False,String extension data type and string data
38,1954720290,MDU6TGFiZWwxOTU0NzIwMjkw,https://api.github.com/repos/pandas-dev/pandas...,Needs Triage,0052cc,False,Issue that has not been reviewed by a pandas t...
39,47223669,MDU6TGFiZWw0NzIyMzY2OQ==,https://api.github.com/repos/pandas-dev/pandas...,Numeric,006b75,False,"Arithmetic, Comparison, and Logical operations"
40,34444536,MDU6TGFiZWwzNDQ0NDUzNg==,https://api.github.com/repos/pandas-dev/pandas...,Usage Question,0052cc,False,None
41,76812,MDU6TGFiZWw3NjgxMg==,https://api.github.com/repos/pandas-dev/pandas...,Enhancement,4E9A06,False,None
42,49254273,MDU6TGFiZWw0OTI1NDI3Mw==,https://api.github.com/repos/pandas-dev/pandas...,IO Excel,bfe5bf,False,"read_excel, to_excel"
43,1728592794,MDU6TGFiZWwxNzI4NTkyNzk0,https://api.github.com/repos/pandas-dev/pandas...,Styler,006b75,False,conditional formatting using DataFrame.style
44,35818298,MDU6TGFiZWwzNTgxODI5OA==,https://api.github.com/repos/pandas-dev/pandas...,API Design,AD7FA8,False,None
45,1465286368,MDU6TGFiZWwxNDY1Mjg2MzY4,https://api.github.com/repos/pandas-dev/pandas...,Constructors,d4c5f9,False,Series/DataFrame/Index/pd.array Constructors
46,76812,MDU6TGFiZWw3NjgxMg==,https://api.github.com/repos/pandas-dev/pandas...,Enhancement,4E9A06,False,None
47,1218227310,MDU6TGFiZWwxMjE4MjI3MzEw,https://api.github.com/repos/pandas-dev/pandas...,Index,e99695,False,Related to the Index class or subclasses
48,1728592794,MDU6TGFiZWwxNzI4NTkyNzk0,https://api.github.com/repos/pandas-dev/pandas...,Styler,006b75,False,conditional formatting using DataFrame.style
49,1741841389,MDU6TGFiZWwxNzQxODQxMzg5,https://api.github.com/repos/pandas-dev/pandas...,API - Consistency,b60205,False,Internal Consistency of API/Behavior
50,1728592794,MDU6TGFiZWwxNzI4NTkyNzk0,https://api.github.com/repos/pandas-dev/pandas...,Styler,006b75,False,conditional formatting using DataFrame.style
51,233160,MDU6TGFiZWwyMzMxNjA=,https://api.github.com/repos/pandas-dev/pandas...,Groupby,729FCF,False,None
52,1218227310,MDU6TGFiZWwxMjE4MjI3MzEw,https://api.github.com/repos/pandas-dev/pandas...,Index,e99695,False,Related to the Index class or subclasses
53,986278782,MDU6TGFiZWw5ODYyNzg3ODI=,https://api.github.com/repos/pandas-dev/pandas...,Needs Tests,cdea3c,False,Unit test(s) needed to prevent regressions
54,717120670,MDU6TGFiZWw3MTcxMjA2NzA=,https://api.github.com/repos/pandas-dev/pandas...,good first issue,0e8a16,True,None
55,31404521,MDU6TGFiZWwzMTQwNDUyMQ==,https://api.github.com/repos/pandas-dev/pandas...,Dtypes,e102d8,False,None
56,1218227310,MDU6TGFiZWwxMjE4MjI3MzEw,https://api.github.com/repos/pandas-dev/pandas...,Index,e99695,False,Related to the Index class or subclasses

In [4]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
data = pd.read_json(url)
data = pd.DataFrame(data, columns=['number','title','user','state','label'])
data.head(5)

# split keys and value in column
import json
from pandas.io.json import json_normalize
user_data = pd.json_normalize(data['user'])
user_data.head(5)

# concating both dataset to display all cloumn
df3 = pd.concat([data[:], user_data[:]], axis=1)
df3.head(5)

# not selecting user column since split\
df4 = pd.concat([data[['number','title','state']], user_data[:]], axis=1)
df4.head(5)

,number,title,state,login,id,node_id,avatar_url,gravatar_id,url,html_url,...,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,41329,DEPS: bump pyarrow min to 1.0,open,jreback,953992,MDQ6VXNlcjk1Mzk5Mg==,https://avatars.githubusercontent.com/u/953992...,,https://api.github.com/users/jreback,https://github.com/jreback,...,https://api.github.com/users/jreback/following...,https://api.github.com/users/jreback/gists{/gi...,https://api.github.com/users/jreback/starred{/...,https://api.github.com/users/jreback/subscript...,https://api.github.com/users/jreback/orgs,https://api.github.com/users/jreback/repos,https://api.github.com/users/jreback/events{/p...,https://api.github.com/users/jreback/received_...,User,False
1,41327,[ArrowStringArray] CLN: remove hasattr checks,open,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
2,41325,ENH: Add dropna argument to pd.DataFrame.value...,open,connesy,13164166,MDQ6VXNlcjEzMTY0MTY2,https://avatars.githubusercontent.com/u/131641...,,https://api.github.com/users/connesy,https://github.com/connesy,...,https://api.github.com/users/connesy/following...,https://api.github.com/users/connesy/gists{/gi...,https://api.github.com/users/connesy/starred{/...,https://api.github.com/users/connesy/subscript...,https://api.github.com/users/connesy/orgs,https://api.github.com/users/connesy/repos,https://api.github.com/users/connesy/events{/p...,https://api.github.com/users/connesy/received_...,User,False
3,41324,BUG: groupby(axis=0).rank(axis=1),open,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
4,41321,ENH: loosen XLS signature,open,geoffrey-eisenbarth,8428345,MDQ6VXNlcjg0MjgzNDU=,https://avatars.githubusercontent.com/u/842834...,,https://api.github.com/users/geoffrey-eisenbarth,https://github.com/geoffrey-eisenbarth,...,https://api.github.com/users/geoffrey-eisenbar...,https://api.github.com/users/geoffrey-eisenbar...,https://api.github.com/users/geoffrey-eisenbar...,https://api.github.com/users/geoffrey-eisenbar...,https://api.github.com/users/geoffrey-eisenbar...,https://api.github.com/users/geoffrey-eisenbar...,https://api.github.com/users/geoffrey-eisenbar...,https://api.github.com/users/geoffrey-eisenbar...,User,False

# Interacting with Databases

In [153]:
import sqlite3
#connecting with the database.
db = sqlite3.connect("my_database4.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists test")
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata2.sqlite')
con.execute(query)
con.commit()

In [154]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [155]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [157]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [158]:
#!/usr/bin/python

import sqlite3
#connecting with the database.
db = sqlite3.connect("my_database5.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists grades1")
# Create table as per requirement
db.execute("create table grades1(id int, name text, score int)")
#inserting values inside the created table
db.execute("insert into grades1(id, name, score) values(101, 'John',99 )")
db.execute("insert into grades1(id, name, score) values(102, 'Gary',90 )")
db.execute("insert into grades1(id, name, score) values(103, 'James', 80 )")
db.execute("insert into grades1(id, name, score) values(104, 'Cathy', 85 )")
db.execute("insert into grades1(id, name, score) values(105, 'Kris',95 )")

In [159]:
db.commit()

In [160]:
results = db.execute("select * from grades1 order by id")
for row in results:
    print((row))
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(103, 'James', 80)
(104, 'Cathy', 85)
(105, 'Kris', 95)
------------------------------------------------------------

In [161]:
results = db.execute("select * from grades1 where name = 'Gary' ")
for row in results: print(row)
print("-"* 60 )

(102, 'Gary', 90)
------------------------------------------------------------

In [162]:
results = db.execute("select * from grades1 where score >= 90 ")
for row in results:
    print(row)
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(105, 'Kris', 95)
------------------------------------------------------------

In [163]:
results = db.execute("select name, score from grades1 order by score desc ")
for row in results:
    print(row)
print("-" * 60 )

('John', 99)
('Kris', 95)
('Gary', 90)
('Cathy', 85)
('James', 80)
------------------------------------------------------------

In [164]:
results = db.execute("select name, score from grades1 order by score")
for row in results:
    print(row)
print("-" * 60 )

('James', 80)
('Cathy', 85)
('Gary', 90)
('Kris', 95)
('John', 99)
------------------------------------------------------------

In [67]:
results = db.execute("select name, score from grades1 order by score")
for row in results:
    print(row)

('James', 80)
('Cathy', 85)
('Gary', 90)
('Kris', 95)
('John', 99)